from __future__ import annotations

import asyncio
from datetime import date
from decimal import Decimal

from app.database import async_session_maker
from app.models.market import MarketSnapshot
from sqlalchemy import select

SEED_DATA = [
    {
        "zip_code": "53081",
        "city": "Sheboygan",
        "state": "WI",
        "median_home_value": Decimal("180000"),
        "median_rent": Decimal("1150"),
        "avg_price_per_sqft": Decimal("115"),
        "avg_days_on_market": 38,
        "inventory_count": 210,
        "avg_cap_rate": Decimal("0.072"),
        "avg_vacancy_rate": Decimal("5.2"),
        "rent_to_price_ratio": Decimal("0.0064"),
        "yoy_appreciation_pct": Decimal("4.1"),
        "population_growth_pct": Decimal("0.3"),
    },
    {
        "zip_code": "53202",
        "city": "Milwaukee",
        "state": "WI",
        "median_home_value": Decimal("220000"),
        "median_rent": Decimal("1350"),
        "avg_price_per_sqft": Decimal("135"),
        "avg_days_on_market": 30,
        "inventory_count": 480,
        "avg_cap_rate": Decimal("0.068"),
        "avg_vacancy_rate": Decimal("6.1"),
        "rent_to_price_ratio": Decimal("0.0061"),
        "yoy_appreciation_pct": Decimal("3.8"),
        "population_growth_pct": Decimal("0.5"),
    },
    {
        "zip_code": "53203",
        "city": "Milwaukee",
        "state": "WI",
        "median_home_value": Decimal("215000"),
        "median_rent": Decimal("1300"),
        "avg_price_per_sqft": Decimal("130"),
        "avg_days_on_market": 32,
        "inventory_count": 310,
        "avg_cap_rate": Decimal("0.066"),
        "avg_vacancy_rate": Decimal("6.5"),
        "rent_to_price_ratio": Decimal("0.0060"),
        "yoy_appreciation_pct": Decimal("3.6"),
        "population_growth_pct": Decimal("0.4"),
    },
    {
        "zip_code": "53204",
        "city": "Milwaukee",
        "state": "WI",
        "median_home_value": Decimal("195000"),
        "median_rent": Decimal("1200"),
        "avg_price_per_sqft": Decimal("122"),
        "avg_days_on_market": 35,
        "inventory_count": 270,
        "avg_cap_rate": Decimal("0.071"),
        "avg_vacancy_rate": Decimal("6.8"),
        "rent_to_price_ratio": Decimal("0.0062"),
        "yoy_appreciation_pct": Decimal("3.5"),
        "population_growth_pct": Decimal("0.2"),
    },
    {
        "zip_code": "53211",
        "city": "Shorewood",
        "state": "WI",
        "median_home_value": Decimal("310000"),
        "median_rent": Decimal("1600"),
        "avg_price_per_sqft": Decimal("180"),
        "avg_days_on_market": 22,
        "inventory_count": 140,
        "avg_cap_rate": Decimal("0.058"),
        "avg_vacancy_rate": Decimal("4.5"),
        "rent_to_price_ratio": Decimal("0.0052"),
        "yoy_appreciation_pct": Decimal("5.2"),
        "population_growth_pct": Decimal("1.1"),
    },
    {
        "zip_code": "53705",
        "city": "Madison",
        "state": "WI",
        "median_home_value": Decimal("350000"),
        "median_rent": Decimal("1750"),
        "avg_price_per_sqft": Decimal("200"),
        "avg_days_on_market": 18,
        "inventory_count": 190,
        "avg_cap_rate": Decimal("0.054"),
        "avg_vacancy_rate": Decimal("3.8"),
        "rent_to_price_ratio": Decimal("0.0050"),
        "yoy_appreciation_pct": Decimal("6.0"),
        "population_growth_pct": Decimal("1.8"),
    },
    {
        "zip_code": "53703",
        "city": "Madison",
        "state": "WI",
        "median_home_value": Decimal("360000"),
        "median_rent": Decimal("1800"),
        "avg_price_per_sqft": Decimal("205"),
        "avg_days_on_market": 17,
        "inventory_count": 175,
        "avg_cap_rate": Decimal("0.055"),
        "avg_vacancy_rate": Decimal("3.5"),
        "rent_to_price_ratio": Decimal("0.0050"),
        "yoy_appreciation_pct": Decimal("6.2"),
        "population_growth_pct": Decimal("2.0"),
    },
    {
        "zip_code": "60601",
        "city": "Chicago",
        "state": "IL",
        "median_home_value": Decimal("330000"),
        "median_rent": Decimal("2100"),
        "avg_price_per_sqft": Decimal("290"),
        "avg_days_on_market": 25,
        "inventory_count": 620,
        "avg_cap_rate": Decimal("0.063"),
        "avg_vacancy_rate": Decimal("5.5"),
        "rent_to_price_ratio": Decimal("0.0064"),
        "yoy_appreciation_pct": Decimal("3.2"),
        "population_growth_pct": Decimal("0.1"),
    },
    {
        "zip_code": "60614",
        "city": "Chicago",
        "state": "IL",
        "median_home_value": Decimal("480000"),
        "median_rent": Decimal("2600"),
        "avg_price_per_sqft": Decimal("380"),
        "avg_days_on_market": 20,
        "inventory_count": 380,
        "avg_cap_rate": Decimal("0.056"),
        "avg_vacancy_rate": Decimal("4.8"),
        "rent_to_price_ratio": Decimal("0.0054"),
        "yoy_appreciation_pct": Decimal("4.0"),
        "population_growth_pct": Decimal("0.5"),
    },
    {
        "zip_code": "48201",
        "city": "Detroit",
        "state": "MI",
        "median_home_value": Decimal("95000"),
        "median_rent": Decimal("900"),
        "avg_price_per_sqft": Decimal("75"),
        "avg_days_on_market": 55,
        "inventory_count": 540,
        "avg_cap_rate": Decimal("0.095"),
        "avg_vacancy_rate": Decimal("10.2"),
        "rent_to_price_ratio": Decimal("0.0095"),
        "yoy_appreciation_pct": Decimal("5.5"),
        "population_growth_pct": Decimal("0.8"),
    },
    {
        "zip_code": "48226",
        "city": "Detroit",
        "state": "MI",
        "median_home_value": Decimal("120000"),
        "median_rent": Decimal("1050"),
        "avg_price_per_sqft": Decimal("90"),
        "avg_days_on_market": 45,
        "inventory_count": 320,
        "avg_cap_rate": Decimal("0.088"),
        "avg_vacancy_rate": Decimal("8.5"),
        "rent_to_price_ratio": Decimal("0.0088"),
        "yoy_appreciation_pct": Decimal("6.0"),
        "population_growth_pct": Decimal("1.0"),
    },
    {
        "zip_code": "55401",
        "city": "Minneapolis",
        "state": "MN",
        "median_home_value": Decimal("290000"),
        "median_rent": Decimal("1650"),
        "avg_price_per_sqft": Decimal("195"),
        "avg_days_on_market": 20,
        "inventory_count": 310,
        "avg_cap_rate": Decimal("0.061"),
        "avg_vacancy_rate": Decimal("4.5"),
        "rent_to_price_ratio": Decimal("0.0057"),
        "yoy_appreciation_pct": Decimal("4.5"),
        "population_growth_pct": Decimal("1.2"),
    },
    {
        "zip_code": "55414",
        "city": "Minneapolis",
        "state": "MN",
        "median_home_value": Decimal("310000"),
        "median_rent": Decimal("1700"),
        "avg_price_per_sqft": Decimal("200"),
        "avg_days_on_market": 19,
        "inventory_count": 280,
        "avg_cap_rate": Decimal("0.059"),
        "avg_vacancy_rate": Decimal("4.2"),
        "rent_to_price_ratio": Decimal("0.0055"),
        "yoy_appreciation_pct": Decimal("4.8"),
        "population_growth_pct": Decimal("1.4"),
    },
    {
        "zip_code": "46201",
        "city": "Indianapolis",
        "state": "IN",
        "median_home_value": Decimal("165000"),
        "median_rent": Decimal("1100"),
        "avg_price_per_sqft": Decimal("105"),
        "avg_days_on_market": 28,
        "inventory_count": 420,
        "avg_cap_rate": Decimal("0.078"),
        "avg_vacancy_rate": Decimal("6.0"),
        "rent_to_price_ratio": Decimal("0.0067"),
        "yoy_appreciation_pct": Decimal("5.8"),
        "population_growth_pct": Decimal("1.5"),
    },
    {
        "zip_code": "44101",
        "city": "Cleveland",
        "state": "OH",
        "median_home_value": Decimal("110000"),
        "median_rent": Decimal("950"),
        "avg_price_per_sqft": Decimal("82"),
        "avg_days_on_market": 42,
        "inventory_count": 390,
        "avg_cap_rate": Decimal("0.090"),
        "avg_vacancy_rate": Decimal("9.0"),
        "rent_to_price_ratio": Decimal("0.0086"),
        "yoy_appreciation_pct": Decimal("4.9"),
        "population_growth_pct": Decimal("0.4"),
    },
]


async def seed() -> None:
    today = date.today()
    async with async_session_maker() as session:
        for data in SEED_DATA:
            existing = await session.execute(
                select(MarketSnapshot).where(
                    MarketSnapshot.zip_code == data["zip_code"],
                    MarketSnapshot.snapshot_date == today,
                    MarketSnapshot.data_source == "seed_data",
                )
            )
            if existing.scalar_one_or_none():
                print(f"  skip  {data['zip_code']} ({data['city']}) — already exists")
                continue
            session.add(
                MarketSnapshot(**data, snapshot_date=today, data_source="seed_data")
            )
            await session.commit()
            print(f"  ✓     {data['zip_code']} {data['city']}, {data['state']}")


if __name__ == "__main__":
    asyncio.run(seed())
